name: mondoo-scan-k8s

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Scan with Mondoo
        uses: mondoohq/actions@main
        with:
          service_account_credentials: ${{ secrets.MONDOO_CLIENT_ACCOUNT }}
          scan_type: k8s
          path: dvwa-eks-deployment.yaml
          output_format: compact